[package]
name = "aoc23"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.14"
typed-arena = "2.0.2"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benches"
harness = false

# [profile.release]
# debug = true

[profile.bench]
debug = false

